[project]
name = "basics-of-blockchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "dotenv>=0.9.9",
    "eth-brownie>=1.21.0",
    "py-solc-x==1.1.1",
    "web3==6.11.0",
    "setuptools<68",
]
